export const ITENS_PER_PAGE = 20;

export const NEARBY_DISTANCE_IN_KILOMETERS = 10;

export const MINUTES_TO_VALIDATE_CHECK_IN = 20;

export const MILLISSECONDS_IN_A_MINUTE = 60 * 1000;

export const MILLISSECONDS_TO_VALIDATE_CHECK_IN =
  MINUTES_TO_VALIDATE_CHECK_IN * MILLISSECONDS_IN_A_MINUTE;
